public without sharing class ECO_Constants {
	public static final String PortalMessage_NewsTickerRecordTypeName = 'News Ticker';
	public static final String PortalMessage_AlertRecordTypeName = 'Alert';
	public static final String PortalMessage_FeedItemRecordTypeName = 'News Feed Item';
	public static final String PortalMessage_OpenProjectReviewMessage = 'You have an open project Review';
	
	public static final String Configuration_ApplicationRecordTypeName = 'Application';
	public static final String Configuration_ApplicationTemplateRecordTypeName = 'Application Template';
	public static final String Configuration_ApplicationReportRecordTypeName = 'Report';
	
	public static final String Contact_PSAResourceRecordTypeName = 'PSA Resource';
	
	public static final String ProjectReview_HealthyStartRecordTypeName = 'Healthy Start/Restart';
	public static final String ProjectReview_HealthyReStartRecordTypeName = 'Healthy Start/Restart';
	public static final String ProjectReview_BatchReviewFrequency = 'Monthly';
	
	public static final String ProjectCloseoutGenericITEmail = 'brent.kendall@nttdata.com';
	
}