public without sharing class ECO_Constants {
	public static final String PortalMessage_NewsTickerRecordTypeName = 'News Ticker';
	public static final String PortalMessage_AlertRecordTypeName = 'Alert';
	public static final String PortalMessage_FeedItemRecordTypeName = 'News Feed Item';
	
	public static final String Configuration_ApplicationRecordTypeName = 'Application';
	public static final String Configuration_ApplicationTemplateRecordTypeName = 'Application Template';
	public static final String Configuration_ApplicationReportRecordTypeName = 'Report';
}