/*************************************************************************
*
* PURPOSE: Controller for the Projects tab in chatter 
*
* CREATED: 2014 Ethos Solutions - www.ethos.com
* AUTHOR: Alex Molina
***************************************************************************/
public with sharing class rsProjectsController extends rsChatterTabController {

	public rsProjectsController() {
		super();
	}
}